### ISSUE TITLE
Resolve External Workarounds

### ISSUE THREAD

**Issue by pi0** [unjs/docs#10]
So the purpose of this tool is to be used as a drop-in tool to write docs and only docs (not a website)! There should be **no workarounds** the the final docs and if any workaround required, it should be done in this repo only.

While testing against some repos (currently [unstorage](https://github.com/unjs/unstorage/tree/main/docs)) with @Atinux we have added some temporary workarounds which I'm listing here to resolve before adopting tool in more repos.

- [x] Public URL needs to be set as `NUXT_PUBLIC_SITE_URL` environment variable
- [x] public dir is essential for assets
- [x] Redirects and route rules defined in `nuxt.config.ts`
- [ ] An extra `package.json` and lockfile is required (zero config CLI might deserve a new issue for followup)

**Comment by Atinux** [comment]
> Public URL needs to be set as NUXT_PUBLIC_SITE_URL environment variable

This is only for production though, normally the module detect the CI env variable to auto assign them:
- https://nuxtseo.com/site-config/getting-started/how-it-works#_3-vendor-environment-variables (also added https://github.com/harlan-zw/nuxt-seo/pull/171)

**Comment by pi0** [comment]
Thanks for PR! I will anyway probably go ahead and add env variables by default to be used by all modules.

**Comment by Atinux** [comment]
Indeed, but only for production I would say!

**Comment by pi0** [comment]
Very basic version of all fixes added. Let's iterate. Also delaying zero install CLI to later.
