### ISSUE TITLE
Add a way to open search bar on mobile

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/docs#17]

**Comment by pi0** [comment]
Is this something we can improve in Nuxt UI/Pro or directly related to our implementation? /cc @benjamincanac

**Comment by Barbapapazes** [comment]
We could hade a button on the header or another the navigation

**Comment by benjamincanac** [comment]
You can use the `UDocsSearchButton` with `label="null"`, it will transform into an icon only button:
![CleanShot 2024-01-25 at 12.32.03@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2024_01_25_at_12_32_03_2x_7e728bba2e.png)

**Comment by pi0** [comment]
Thanks for the tip @benjamincanac!

One question would it also hide the keyboard shortcuts when there is no keyboard attached to like when using on mobile?

Interesting found experimental keyboard API: https://developer.mozilla.org/en-US/docs/Web/API/Keyboard_API (and some [funny](https://stackoverflow.com/questions/18880236/how-do-i-detect-hardware-keyboard-presence-with-javascript) answers too!)

**Comment by benjamincanac** [comment]
In my screenshot the tooltip is added manually: https://github.com/nuxt/ui/blob/dev/docs/components/Header.vue#L18

**Comment by benjamincanac** [comment]
The `UTooltip` component from `@nuxt/ui` is hidden on mobile by default.
