### ISSUE TITLE
Do not remove the first sentence to use it as a description

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/docs#18]

**Comment by pi0** [comment]
Can you please provide more details in meanwhile @Barbapapazes. Also /cc @Atinux as he has most knowledge on this.

**Comment by Barbapapazes** [comment]
Head of my markdown file

![image](https://github.com/unjs/docs/assets/45267552/64742647-d80e-45ea-8c3a-18c064f4a8b8)

Head of rendered file

![image](https://github.com/unjs/docs/assets/45267552/3946049e-1342-4362-aa6d-63856abfa434)

**Comment by Barbapapazes** [comment]
Unable to reproduce in Nuxt Content nor MDC

**Comment by Barbapapazes** [comment]
It's related to the nitro plugin: https://github.com/unjs/docs/blob/main/app/server/plugins/content.ts

**Comment by Barbapapazes** [comment]
BTW this issue does exist only because Nuxt UI Pro use the description in the PageHeader component. This is not a bad thing but the header description is more like the og-description (so must be SEO friendly) than the first p in a md file.

I think that user should write a description in front-matter to have a correct description.
