### ISSUE TITLE
Footer styling bug

### ISSUE THREAD

**Issue by cpreston321** [unjs/docs#28]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.10.0`
- Nuxt Version:     `-`
- CLI Version:      `3.10.0`
- Nitro Version:    `-`
- Package Manager:  `pnpm@8.15.0`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Live: https://crossws.unjs.io/

Repo: https://github.com/unjs/crossws

### Describe the bug

The footer seems to be weirdly placed when using as a dependency. Just go to https://github.com/unjs/crossws run doc in dev mode and you will see the same issue.

### Additional context

![CleanShot 2024-01-29 at 13 25 02@2x](https://github.com/unjs/docs/assets/6619884/b5b814a7-e5d6-4102-ae00-f7920c0f17ce)

### Logs

```sh
[Vue warn]: Invalid prop: type check failed for prop "value". Expected String | Object, got Undefined
```

**Comment by pi0** [comment]
Thanks for reporting (also sharp eyes on new docs 👀)

I could successfully break `unjs/docs` too by renewing lockfile (https://github.com/unjs/docs/commit/313c37f406eee0a406cebbb1c6c194b046e01a9c). So seems a regression somewhere out there.

/cc @benjamincanac @Atinux pinging if you have any guesses.

**Comment by benjamincanac** [comment]
Not sure to understand, you're not using the [`UFooter`](https://ui.nuxt.com/pro/components/footer/footer) component from `@nuxt/ui-pro` here 🤔

**Comment by pi0** [comment]
Fixed by https://github.com/unjs/docs/commit/28df1e1ed3bcb235289d1cc922675e041384d9dd
