### ISSUE TITLE
Move `docs.config.ts` to custom module within `app/modules`

### ISSUE THREAD

**Issue by cpreston321** [unjs/docs#30]
### Describe the feature

The benefit to having it this way to support HMR on the `docs.config.ts` as of right now it doesn't watch for changes on the file. 

The downside have to restart to see changes when changed, but I don't know if that is a huge deal right now but it would be a enhancement for long term use case if more changes are going to be moved into that config. 

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi. yes I am aware of this limitation but this is a temporary solution since we need config both in build time and runtime. In the future I am thinking to leverage virtual app config to allow HMR when can.

**Comment by pi0** [comment]
Made https://github.com/unjs/docs/issues/31 to track
